# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nexus_integration_pb2 as nexus__integration__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nexus_integration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NexusSearchStub:
    """===== ОСНОВНОЙ СЕРВИС =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/nexus.integration.NexusSearch/Search',
                request_serializer=nexus__integration__pb2.SearchRequest.SerializeToString,
                response_deserializer=nexus__integration__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Ingest = channel.unary_unary(
                '/nexus.integration.NexusSearch/Ingest',
                request_serializer=nexus__integration__pb2.IngestRequest.SerializeToString,
                response_deserializer=nexus__integration__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.ScanProject = channel.unary_unary(
                '/nexus.integration.NexusSearch/ScanProject',
                request_serializer=nexus__integration__pb2.ScanProjectRequest.SerializeToString,
                response_deserializer=nexus__integration__pb2.ScanProjectResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/nexus.integration.NexusSearch/HealthCheck',
                request_serializer=nexus__integration__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=nexus__integration__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ApplyConfig = channel.unary_unary(
                '/nexus.integration.NexusSearch/ApplyConfig',
                request_serializer=nexus__integration__pb2.ConfigRequest.SerializeToString,
                response_deserializer=nexus__integration__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/nexus.integration.NexusSearch/Shutdown',
                request_serializer=nexus__integration__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=nexus__integration__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class NexusSearchServicer:
    """===== ОСНОВНОЙ СЕРВИС =====

    """

    def Search(self, request, context):
        """Быстрый полнотекстовый поиск по проектам и документам
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ingest(self, request, context):
        """Индексирование документа или файла
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanProject(self, request, context):
        """Сканирование и индексирование проекта
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Проверка здоровья системы
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyConfig(self, request, context):
        """Применить конфигурацию (отключить auto-update и т.д.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Graceful shutdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NexusSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=nexus__integration__pb2.SearchRequest.FromString,
                    response_serializer=nexus__integration__pb2.SearchResponse.SerializeToString,
            ),
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=nexus__integration__pb2.IngestRequest.FromString,
                    response_serializer=nexus__integration__pb2.IngestResponse.SerializeToString,
            ),
            'ScanProject': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanProject,
                    request_deserializer=nexus__integration__pb2.ScanProjectRequest.FromString,
                    response_serializer=nexus__integration__pb2.ScanProjectResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=nexus__integration__pb2.HealthCheckRequest.FromString,
                    response_serializer=nexus__integration__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ApplyConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyConfig,
                    request_deserializer=nexus__integration__pb2.ConfigRequest.FromString,
                    response_serializer=nexus__integration__pb2.ConfigResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=nexus__integration__pb2.ShutdownRequest.FromString,
                    response_serializer=nexus__integration__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.integration.NexusSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.integration.NexusSearch', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NexusSearch:
    """===== ОСНОВНОЙ СЕРВИС =====

    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.integration.NexusSearch/Search',
            nexus__integration__pb2.SearchRequest.SerializeToString,
            nexus__integration__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.integration.NexusSearch/Ingest',
            nexus__integration__pb2.IngestRequest.SerializeToString,
            nexus__integration__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.integration.NexusSearch/ScanProject',
            nexus__integration__pb2.ScanProjectRequest.SerializeToString,
            nexus__integration__pb2.ScanProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.integration.NexusSearch/HealthCheck',
            nexus__integration__pb2.HealthCheckRequest.SerializeToString,
            nexus__integration__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.integration.NexusSearch/ApplyConfig',
            nexus__integration__pb2.ConfigRequest.SerializeToString,
            nexus__integration__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.integration.NexusSearch/Shutdown',
            nexus__integration__pb2.ShutdownRequest.SerializeToString,
            nexus__integration__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
